
stages:
    - test

before_script:
    - |
        if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
            export ENV=prod
        else
            export ENV=dev
        fi

.tests: &tests
    stage: test
    script:
        - R CMD build . --no-build-vignettes --no-manual
        - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
        - R CMD check "$PKG_FILE_NAME" --no-build-vignettes --no-manual
    artifacts:
        when: on_failure
        paths:
            - ./*.Rcheck/00check.log

check_dev:
    <<: *tests
    image: rocker/tidyverse
    except:
        - master

check_prod:
    <<: *tests
    image: rocker/tidyverse
    only:
        - master
